services:
  backend:
    build:
      context: ./grocerylist
    container_name: grocery-backend
    ports:
      - "8000:8000"
    volumes:
      - ./grocerylist:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./grocerylist-frontend
    container_name: grocery-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./grocerylist-frontend:/app
    command: npm start -- --host 0.0.0.0
    depends_on:
      - backend
